"""
Predefined Data for Testing
"""

ROLES = [
    {"id": 1, "name": "shop"}, {"id": 2, "name": "customer"}
]

CATEGORIES = [{"id": 1, "name": "bowed strings"}, {"id": 2, "name": "pucked strings"},
    {"id": 3, "name": "woodwinds"}, {"id": 4, "name": "brass"},
    {"id": 5, "name": "percussion"}, {"id": 6, "name": "keyboards"},
    {"id": 7, "name": "repairment"}, {"id": 8, "name": "maintenance"},
    {"id": 9, "name": "sound"}]

USERS = [
    {"id": 1, "email": "incognito@gmail.com", "username": "Incognito", "password": "123456", "role_id": 2, "confirmed": True,
     "avatar_path": '../static/img/no-image.png'},
    {"id": 2, "email": "bcd234@gmail.com", "username": "bcd234", "password": "123456", "role_id": 2, "confirmed": True,
     "avatar_path": "../static/storage/avatars/default_avatar.jpg"},
    {"id": 3, "email": "abc123@gmail.com", "username": "abc123", "password": "123456", "role_id": 1, "confirmed": True,
     "avatar_path": "../static/storage/avatars/default_avatar.jpg"},
    {"id": 4, "email": "wuyunze@gmail.com", "username": "wuyunze", "password": "123456", "role_id": 2, "confirmed": True,
     "avatar_path": "../static/storage/avatars/avatar_admin.jpg"},
]

PRODUCTS = [
    {"id": 1, "model": "Acura", "bland": "RLX", "year": "2014", "description": "This is a test car."},
    {"id": 2, "model": "Nissan", "bland": "cube", "year": "2009", "description": "This is a test car."},
    {"id": 3, "model": "Chevrolet", "bland": "Captiva Sport", "year": "2014", "description": "This is a test car."},
    {"id": 4, "model": "Jaguar", "bland": "F-TYPE", "year": "2015", "description": "This is a test car."},
    {"id": 5, "model": "Cadillac", "bland": "CTS-V", "year": "2009", "description": "This is a test car."},
    {"id": 6, "model": "Mazda", "bland": "Mazda3", "year": "2014", "description": "This is a test car."},
    {"id": 7, "model": "Ford", "bland": "Ranger", "year": "2011", "description": "This is a test car."},
    {"id": 8, "model": "MINI", "bland": "Cooper", "year": "2009", "description": "This is a test car."},
    {"id": 9, "model": "Audi", "bland": "A4", "year": "2014", "description": "This is a test car."},
    {"id": 10, "model": "Hyundai", "bland": "Sonata Hybrid", "year": "2016", "description": "This is a test car."},
    {"id": 11, "model": "MINI", "bland": "Countryman", "year": "2016", "description": "This is a test car."},
    {"id": 12, "model": "Honda", "bland": "Accord Crosstour", "year": "2011", "description": "This is a test car."},
    {"id": 13, "model": "Dodge", "bland": "Challenger", "year": "2013", "description": "This is a test car."},
    {"id": 14, "model": "Hyundai", "bland": "Azera", "year": "2016", "description": "This is a test car."},
    {"id": 15, "model": "Ford", "bland": "F-250 Super Duty", "year": "2012", "description": "This is a test car."},
    {"id": 16, "model": "INFINITI", "bland": "Q50", "year": "2014", "description": "This is a test car."},
    {"id": 17, "model": "BMW", "bland": "5 Series", "year": "2014", "description": "This is a test car."},
    {"id": 18, "model": "Mazda", "bland": "CX-7", "year": "2010", "description": "This is a test car."},
    {"id": 19, "model": "INFINITI", "bland": "G35", "year": "2008", "description": "This is a test car."},
    {"id": 20, "model": "Chevrolet", "bland": "Cobalt", "year": "2009", "description": "This is a test car."},
    {"id": 21, "model": "Mercedes-Benz", "bland": "CLA-Class", "year": "2014", "description": "This is a test car."},
    {"id": 22, "model": "Kia", "bland": "Forte", "year": "2014", "description": "This is a test car."},
    {"id": 23, "model": "Ford", "bland": "Fusion", "year": "2015", "description": "This is a test car."},
    {"id": 24, "model": "Ford", "bland": "Expedition", "year": "2013", "description": "This is a test car."},
    {"id": 25, "model": "Jeep", "bland": "Compass", "year": "2015", "description": "This is a test car."},
    {"id": 26, "model": "Lexus", "bland": "HS 250h", "year": "2012", "description": "This is a test car."},
    {"id": 27, "model": "Ford", "bland": "Taurus", "year": "2016", "description": "This is a test car."},
    {"id": 28, "model": "Jeep", "bland": "Grand Cherokee", "year": "2016", "description": "This is a test car."},
    {"id": 29, "model": "Mitsubishi", "bland": "i-MiEV", "year": "2012", "description": "This is a test car."},
    {"id": 30, "model": "Kia", "bland": "Soul", "year": "2016", "description": "This is a test car."},
    {"id": 31, "model": "Ford", "bland": "Fusion Hybrid", "year": "2015", "description": "This is a test car."},
    {"id": 32, "model": "Mazda", "bland": "CX-7", "year": "2011", "description": "This is a test car."},
    {"id": 33, "model": "Honda", "bland": "Fit", "year": "2013", "description": "This is a test car."},
    {"id": 34, "model": "Ford", "bland": "Mustang", "year": "2014", "description": "This is a test car."},
    {"id": 35, "model": "Jaguar", "bland": "XJ", "year": "2013", "description": "This is a test car."},
    {"id": 36, "model": "Kia", "bland": "Sorento", "year": "2016", "description": "This is a test car."},
    {"id": 37, "model": "Mazda", "bland": "CX-5", "year": "2014", "description": "This is a test car."},
    {"id": 38, "model": "Land Rover", "bland": "Range Rover Sport", "year": "2012",
     "description": "This is a test car."},
    {"id": 39, "model": "Mercedes-Benz", "bland": "CLA", "year": "2015", "description": "This is a test car."},
    {"id": 40, "model": "Lexus", "bland": "RC 300", "year": "2016", "description": "This is a test car."},
    {"id": 41, "model": "Lincoln", "bland": "Navigator L", "year": "2015", "description": "This is a test car."},
    {"id": 42, "model": "Jaguar", "bland": "XF", "year": "2013", "description": "This is a test car."},
    {"id": 43, "model": "Mazda", "bland": "Mazda2", "year": "2011", "description": "This is a test car."},
    {"id": 44, "model": "Lexus", "bland": "IS 350", "year": "2015", "description": "This is a test car."},
    {"id": 45, "model": "Mitsubishi", "bland": "Lancer", "year": "2016", "description": "This is a test car."},
    {"id": 46, "model": "GMC", "bland": "Acadia", "year": "2013", "description": "This is a test car."},
    {"id": 47, "model": "INFINITI", "bland": "G37", "year": "2008", "description": "This is a test car."},
    {"id": 48, "model": "Lexus", "bland": "RX 450h", "year": "2015", "description": "This is a test car."},
    {"id": 49, "model": "MINI", "bland": "Cooper Hardtop", "year": "2012", "description": "This is a test car."},
    {"id": 50, "model": "Mazda", "bland": "CX-9", "year": "2010", "description": "This is a test car."},
    {"id": 51, "model": "Kia", "bland": "Forte Koup", "year": "2014", "description": "This is a test car."},
    {"id": 52, "model": "Chevrolet", "bland": "Impala", "year": "2014", "description": "This is a test car."},
    {"id": 53, "model": "Dodge", "bland": "Journey", "year": "2014", "description": "This is a test car."},
    {"id": 54, "model": "Ford", "bland": "Shelby GT500", "year": "2011", "description": "This is a test car."},
    {"id": 55, "model": "GMC", "bland": "Canyon", "year": "2015", "description": "This is a test car."},
    {"id": 56, "model": "Dodge", "bland": "Ram Pickup 1500", "year": "2007", "description": "This is a test car."},
    {"id": 57, "model": "INFINITI", "bland": "G25 Sedan", "year": "2012", "description": "This is a test car."},
    {"id": 58, "model": "BMW", "bland": "1 Series", "year": "2009", "description": "This is a test car."},
    {"id": 59, "model": "Mitsubishi", "bland": "Lancer Evolution", "year": "2011",
     "description": "This is a test car."},
    {"id": 60, "model": "Honda", "bland": "CR-Z", "year": "2014", "description": "This is a test car."},
    {"id": 61, "model": "Hyundai", "bland": "Elantra GT", "year": "2013", "description": "This is a test car."},
    {"id": 62, "model": "Mercedes-Benz", "bland": "GLK-Class", "year": "2014", "description": "This is a test car."},
    {"id": 63, "model": "Ford", "bland": "Mustang", "year": "2016", "description": "This is a test car."},
    {"id": 64, "model": "Land Rover", "bland": "Range Rover Evoque Coupe", "year": "2014",
     "description": "This is a test car."},
    {"id": 65, "model": "INFINITI", "bland": "QX50", "year": "2015", "description": "This is a test car."},
    {"id": 66, "model": "Jeep", "bland": "Wrangler Unlimited", "year": "2013", "description": "This is a test car."},
    {"id": 67, "model": "Mazda", "bland": "Mazda5", "year": "2012", "description": "This is a test car."},
    {"id": 68, "model": "GMC", "bland": "Acadia", "year": "2014", "description": "This is a test car."},
    {"id": 69, "model": "Ford", "bland": "Fusion", "year": "2013", "description": "This is a test car."},
    {"id": 70, "model": "Jeep", "bland": "Grand Cherokee", "year": "2015", "description": "This is a test car."},
    {"id": 71, "model": "Hyundai", "bland": "Genesis", "year": "2014", "description": "This is a test car."},
    {"id": 72, "model": "Lexus", "bland": "IS 300", "year": "2016", "description": "This is a test car."},
    {"id": 73, "model": "INFINITI", "bland": "EX35", "year": "2012", "description": "This is a test car."},
    {"id": 74, "model": "Audi", "bland": "A8 L", "year": "2014", "description": "This is a test car."},
    {"id": 75, "model": "Cadillac", "bland": "ATS", "year": "2014", "description": "This is a test car."},
    {"id": 76, "model": "INFINITI", "bland": "Q70", "year": "2015", "description": "This is a test car."},
    {"id": 77, "model": "Lexus", "bland": "IS 200t", "year": "2016", "description": "This is a test car."},
    {"id": 78, "model": "Ford", "bland": "C-MAX Hybrid", "year": "2015", "description": "This is a test car."},
    {"id": 79, "model": "FIAT", "bland": "500", "year": "2013", "description": "This is a test car."},
    {"id": 80, "model": "Kia", "bland": "Sportage", "year": "2014", "description": "This is a test car."},
    {"id": 81, "model": "Lexus", "bland": "SC 430", "year": "2009", "description": "This is a test car."},
    {"id": 82, "model": "Audi", "bland": "A4", "year": "2011", "description": "This is a test car."},
    {"id": 83, "model": "Lexus", "bland": "IS 250C", "year": "2012", "description": "This is a test car."},
    {"id": 84, "model": "Acura", "bland": "TSX Sport Wagon", "year": "2013", "description": "This is a test car."},
    {"id": 85, "model": "Audi", "bland": "TT RS", "year": "2012", "description": "This is a test car."},
    {"id": 86, "model": "Chevrolet", "bland": "Silverado 1500", "year": "2016", "description": "This is a test car."},
    {"id": 87, "model": "BMW", "bland": "X3", "year": "2016", "description": "This is a test car."},
    {"id": 88, "model": "Lexus", "bland": "ES 300h", "year": "2014", "description": "This is a test car."},
    {"id": 89, "model": "FIAT", "bland": "500L", "year": "2014", "description": "This is a test car."},
    {"id": 90, "model": "Mercedes-Benz", "bland": "SLK", "year": "2016", "description": "This is a test car."},
    {"id": 91, "model": "Honda", "bland": "Accord Plug-In", "year": "2014", "description": "This is a test car."},
    {"id": 92, "model": "Chevrolet", "bland": "Equinox", "year": "2014", "description": "This is a test car."},
    {"id": 93, "model": "Audi", "bland": "A7", "year": "2015", "description": "This is a test car."},
    {"id": 94, "model": "Lexus", "bland": "RC 350", "year": "2015", "description": "This is a test car."},
    {"id": 95, "model": "Kia", "bland": "Sorento", "year": "2014", "description": "This is a test car."},
    {"id": 96, "model": "Lincoln", "bland": "Navigator", "year": "2015", "description": "This is a test car."},
    {"id": 97, "model": "Cadillac", "bland": "DTS", "year": "2011", "description": "This is a test car."},
    {"id": 98, "model": "Audi", "bland": "TT", "year": "2016", "description": "This is a test car."},
    {"id": 99, "model": "MINI", "bland": "Cooper Clubman", "year": "2011", "description": "This is a test car."},
    {"id": 100, "model": "Hyundai", "bland": "Accent", "year": "2016", "description": "This is a test car."},
    {"id": 101, "model": "MINI", "bland": "Hardtop", "year": "2014", "description": "This is a test car."},
    {"id": 102, "model": "Cadillac", "bland": "Escalade ESV", "year": "2014", "description": "This is a test car."},
    {"id": 103, "model": "MINI", "bland": "Convertible", "year": "2016", "description": "This is a test car."},
    {"id": 104, "model": "Cadillac", "bland": "Escalade", "year": "2013", "description": "This is a test car."},
    {"id": 105, "model": "Dodge", "bland": "Avenger", "year": "2013", "description": "This is a test car."},
    {"id": 106, "model": "Ford", "bland": "Fusion Energi", "year": "2015", "description": "This is a test car."},
    {"id": 107, "model": "Audi", "bland": "TT", "year": "2016", "description": "This is a test car."},
    {"id": 108, "model": "Kia", "bland": "Spectra", "year": "2007", "description": "This is a test car."},
    {"id": 109, "model": "Mitsubishi", "bland": "Endeavor", "year": "2010", "description": "This is a test car."},
    {"id": 110, "model": "Buick", "bland": "LaCrosse", "year": "2016", "description": "This is a test car."},
    {"id": 111, "model": "Chevrolet", "bland": "Avalanche", "year": "2011", "description": "This is a test car."},
    {"id": 112, "model": "Lincoln", "bland": "Town Car", "year": "2009", "description": "This is a test car."},
    {"id": 113, "model": "Audi", "bland": "Q7", "year": "2010", "description": "This is a test car."},
    {"id": 114, "model": "Audi", "bland": "SQ5", "year": "2014", "description": "This is a test car."},
    {"id": 115, "model": "Lexus", "bland": "LS 460", "year": "2009", "description": "This is a test car."},
    {"id": 116, "model": "Honda", "bland": "Pilot", "year": "2013", "description": "This is a test car."},
    {"id": 117, "model": "Ford", "bland": "Edge", "year": "2013", "description": "This is a test car."},
    {"id": 118, "model": "Mercedes-Benz", "bland": "E-Class", "year": "2015", "description": "This is a test car."},
    {"id": 119, "model": "Mazda", "bland": "Tribute", "year": "2008", "description": "This is a test car."},
    {"id": 120, "model": "Jeep", "bland": "Liberty", "year": "2011", "description": "This is a test car."},
    {"id": 121, "model": "Buick", "bland": "Enclave", "year": "2014", "description": "This is a test car."},
    {"id": 122, "model": "Mercedes-Benz", "bland": "GLK-Class", "year": "2011", "description": "This is a test car."},
    {"id": 123, "model": "INFINITI", "bland": "FX35", "year": "2011", "description": "This is a test car."},
    {"id": 124, "model": "Chevrolet", "bland": "Silverado 1500", "year": "2013", "description": "This is a test car."},
    {"id": 125, "model": "Chevrolet", "bland": "Camaro", "year": "2010", "description": "This is a test car."},
    {"id": 126, "model": "Kia", "bland": "Sportage", "year": "2016", "description": "This is a test car."},
    {"id": 127, "model": "BMW", "bland": "4 Series", "year": "2014", "description": "This is a test car."},
    {"id": 128, "model": "Chevrolet", "bland": "Suburban", "year": "2015", "description": "This is a test car."},
    {"id": 129, "model": "INFINITI", "bland": "Q70L", "year": "2015", "description": "This is a test car."},
    {"id": 130, "model": "Ford", "bland": "Explorer", "year": "2016", "description": "This is a test car."},
    {"id": 131, "model": "Mitsubishi", "bland": "Lancer", "year": "2015", "description": "This is a test car."},
    {"id": 132, "model": "Acura", "bland": "TSX Sport Wagon", "year": "2011", "description": "This is a test car."},
    {"id": 133, "model": "Audi", "bland": "Q5", "year": "2014", "description": "This is a test car."},
    {"id": 134, "model": "Kia", "bland": "Cadenza", "year": "2014", "description": "This is a test car."},
    {"id": 135, "model": "Jeep", "bland": "Patriot", "year": "2015", "description": "This is a test car."},
    {"id": 136, "model": "Lincoln", "bland": "Navigator L", "year": "2015", "description": "This is a test car."},
    {"id": 137, "model": "Chevrolet", "bland": "Captiva Sport", "year": "2015", "description": "This is a test car."},
    {"id": 138, "model": "Chrysler", "bland": "200 Convertible", "year": "2012", "description": "This is a test car."},
    {"id": 139, "model": "Jaguar", "bland": "XJL", "year": "2012", "description": "This is a test car."},
    {"id": 140, "model": "BMW", "bland": "5 Series", "year": "2013", "description": "This is a test car."},
    {"id": 141, "model": "Ford", "bland": "C-MAX Energi", "year": "2015", "description": "This is a test car."},
    {"id": 142, "model": "Dodge", "bland": "Durango", "year": "2016", "description": "This is a test car."},
    {"id": 143, "model": "Nissan", "bland": "370Z", "year": "2014", "description": "This is a test car."},
    {"id": 144, "model": "Acura", "bland": "TLX", "year": "2016", "description": "This is a test car."},
    {"id": 145, "model": "INFINITI", "bland": "FX37", "year": "2013", "description": "This is a test car."},
    {"id": 146, "model": "MINI", "bland": "Cooper Coupe", "year": "2012", "description": "This is a test car."},
    {"id": 147, "model": "INFINITI", "bland": "M35", "year": "2009", "description": "This is a test car."},
    {"id": 148, "model": "Chrysler", "bland": "200", "year": "2016", "description": "This is a test car."},
    {"id": 149, "model": "Kia", "bland": "Forte Koup", "year": "2015", "description": "This is a test car."},
    {"id": 150, "model": "INFINITI", "bland": "JX35", "year": "2013", "description": "This is a test car."},
    {"id": 151, "model": "Acura", "bland": "ILX", "year": "2014", "description": "This is a test car."},
    {"id": 152, "model": "Mercedes-Benz", "bland": "GL-Class", "year": "2013", "description": "This is a test car."},
    {"id": 153, "model": "Kia", "bland": "Forte", "year": "2016", "description": "This is a test car."},
    {"id": 154, "model": "Lexus", "bland": "CT 200h", "year": "2014", "description": "This is a test car."},
    {"id": 155, "model": "Lincoln", "bland": "MKX", "year": "2016", "description": "This is a test car."},
    {"id": 156, "model": "Mitsubishi", "bland": "Lancer Evolution", "year": "2014",
     "description": "This is a test car."},
    {"id": 157, "model": "Mercedes-Benz", "bland": "S-Class", "year": "2013", "description": "This is a test car."},
    {"id": 158, "model": "Honda", "bland": "Accord Hybrid", "year": "2015", "description": "This is a test car."},
    {"id": 159, "model": "Mercedes-Benz", "bland": "CL-Class", "year": "2011", "description": "This is a test car."},
    {"id": 160, "model": "Jeep", "bland": "Patriot", "year": "2016", "description": "This is a test car."},
    {"id": 161, "model": "FIAT", "bland": "500L", "year": "2015", "description": "This is a test car."},
    {"id": 162, "model": "INFINITI", "bland": "QX60 Hybrid", "year": "2014", "description": "This is a test car."},
    {"id": 163, "model": "INFINITI", "bland": "G Coupe", "year": "2013", "description": "This is a test car."},
    {"id": 164, "model": "INFINITI", "bland": "G37 Coupe", "year": "2012", "description": "This is a test car."},
    {"id": 165, "model": "BMW", "bland": "X1", "year": "2015", "description": "This is a test car."},
    {"id": 166, "model": "Audi", "bland": "TTS", "year": "2012", "description": "This is a test car."},
    {"id": 167, "model": "GMC", "bland": "Sierra 1500", "year": "2016", "description": "This is a test car."},
    {"id": 168, "model": "Mercedes-Benz", "bland": "CL-Class", "year": "2011", "description": "This is a test car."},
    {"id": 169, "model": "Acura", "bland": "ZDX", "year": "2010", "description": "This is a test car."},
    {"id": 170, "model": "Acura", "bland": "TSX", "year": "2014", "description": "This is a test car."},
    {"id": 171, "model": "Audi", "bland": "S5", "year": "2009", "description": "This is a test car."},
    {"id": 172, "model": "Buick", "bland": "Verano", "year": "2015", "description": "This is a test car."},
    {"id": 173, "model": "Mazda", "bland": "MAZDASPEED3", "year": "2012", "description": "This is a test car."},
    {"id": 174, "model": "Cadillac", "bland": "Escalade ESV", "year": "2013", "description": "This is a test car."},
    {"id": 175, "model": "Jeep", "bland": "Renegade", "year": "2016", "description": "This is a test car."},
    {"id": 176, "model": "Hyundai", "bland": "Tucson", "year": "2016", "description": "This is a test car."},
    {"id": 177, "model": "Mazda", "bland": "CX-5", "year": "2016", "description": "This is a test car."},
    {"id": 178, "model": "Hyundai", "bland": "Santa Fe Sport", "year": "2016", "description": "This is a test car."},
    {"id": 179, "model": "Dodge", "bland": "Caliber", "year": "2011", "description": "This is a test car."},
    {"id": 180, "model": "Chevrolet", "bland": "SS", "year": "2014", "description": "This is a test car."},
    {"id": 181, "model": "Honda", "bland": "Ridgeline", "year": "2014", "description": "This is a test car."},
    {"id": 182, "model": "Ford", "bland": "Focus", "year": "2010", "description": "This is a test car."},
    {"id": 183, "model": "Chevrolet", "bland": "Cruze", "year": "2015", "description": "This is a test car."},
    {"id": 184, "model": "GMC", "bland": "Terrain", "year": "2015", "description": "This is a test car."},
    {"id": 185, "model": "Chevrolet", "bland": "Spark", "year": "2015", "description": "This is a test car."},
    {"id": 186, "model": "Cadillac", "bland": "ELR", "year": "2014", "description": "This is a test car."},
    {"id": 187, "model": "Chevrolet", "bland": "Malibu Limited", "year": "2016", "description": "This is a test car."},
    {"id": 188, "model": "Kia", "bland": "K900", "year": "2015", "description": "This is a test car."},
    {"id": 189, "model": "BMW", "bland": "4 Series", "year": "2016", "description": "This is a test car."},
    {"id": 190, "model": "Acura", "bland": "ZDX", "year": "2010", "description": "This is a test car."},
    {"id": 191, "model": "Cadillac", "bland": "XTS", "year": "2014", "description": "This is a test car."},
    {"id": 192, "model": "Chevrolet", "bland": "Spark EV", "year": "2014", "description": "This is a test car."},
    {"id": 193, "model": "Mercedes-Benz", "bland": "E-Class", "year": "2014", "description": "This is a test car."},
    {"id": 194, "model": "Lincoln", "bland": "MKS", "year": "2013", "description": "This is a test car."},
    {"id": 195, "model": "Dodge", "bland": "Dart", "year": "2016", "description": "This is a test car."},
    {"id": 196, "model": "Kia", "bland": "K900", "year": "2015", "description": "This is a test car."},
    {"id": 197, "model": "GMC", "bland": "Yukon XL", "year": "2011", "description": "This is a test car."},
    {"id": 198, "model": "Chevrolet", "bland": "Black Diamond Avalanche", "year": "2013",
     "description": "This is a test car."},
    {"id": 199, "model": "Chrysler", "bland": "300", "year": "2016", "description": "This is a test car."},
    {"id": 200, "model": "Audi", "bland": "RS 5", "year": "2013", "description": "This is a test car."},
    {"id": 201, "model": "FIAT", "bland": "500e", "year": "2013", "description": "This is a test car."},
    {"id": 202, "model": "INFINITI", "bland": "Q50", "year": "2016", "description": "This is a test car."},
    {"id": 203, "model": "Audi", "bland": "A3", "year": "2016", "description": "This is a test car."},
    {"id": 204, "model": "Lexus", "bland": "HS 250h", "year": "2011", "description": "This is a test car."},
    {"id": 205, "model": "Maserati", "bland": "Ghibli", "year": "2015", "description": "This is a test car."},
    {"id": 206, "model": "Land Rover", "bland": "Discovery Sport", "year": "2015",
     "description": "This is a test car."},
    {"id": 207, "model": "BMW", "bland": "X1", "year": "2014", "description": "This is a test car."},
    {"id": 208, "model": "Audi", "bland": "A6", "year": "2013", "description": "This is a test car."},
    {"id": 209, "model": "INFINITI", "bland": "G37 Convertible", "year": "2013", "description": "This is a test car."},
    {"id": 210, "model": "Chevrolet", "bland": "Traverse", "year": "2016", "description": "This is a test car."},
    {"id": 211, "model": "BMW", "bland": "X3", "year": "2014", "description": "This is a test car."},
    {"id": 212, "model": "Honda", "bland": "Civic", "year": "2016", "description": "This is a test car."},
    {"id": 213, "model": "Kia", "bland": "Rio5", "year": "2014", "description": "This is a test car."},
    {"id": 214, "model": "BMW", "bland": "2 Series", "year": "2016", "description": "This is a test car."},
    {"id": 215, "model": "INFINITI", "bland": "QX50", "year": "2015", "description": "This is a test car."},
    {"id": 216, "model": "Lexus", "bland": "RC 200t", "year": "2016", "description": "This is a test car."},
    {"id": 217, "model": "Dodge", "bland": "Ram Pickup 2500", "year": "2006", "description": "This is a test car."},
    {"id": 218, "model": "Honda", "bland": "Crosstour", "year": "2013", "description": "This is a test car."},
    {"id": 219, "model": "Mercedes-Benz", "bland": "CLK", "year": "2009", "description": "This is a test car."},
    {"id": 220, "model": "Cadillac", "bland": "ATS", "year": "2016", "description": "This is a test car."},
    {"id": 221, "model": "Nissan", "bland": "370Z", "year": "2016", "description": "This is a test car."},
    {"id": 222, "model": "Lexus", "bland": "NX 200t", "year": "2016", "description": "This is a test car."},
    {"id": 223, "model": "Mercury", "bland": "Grand Marquis", "year": "2008", "description": "This is a test car."},
    {"id": 224, "model": "MINI", "bland": "Convertible", "year": "2016", "description": "This is a test car."},
    {"id": 225, "model": "Chevrolet", "bland": "Volt", "year": "2012", "description": "This is a test car."},
    {"id": 226, "model": "Lincoln", "bland": "MKT", "year": "2016", "description": "This is a test car."},
    {"id": 227, "model": "Lincoln", "bland": "MKC", "year": "2015", "description": "This is a test car."},
    {"id": 228, "model": "Ford", "bland": "Fiesta", "year": "2015", "description": "This is a test car."},
    {"id": 229, "model": "BMW", "bland": "X4", "year": "2015", "description": "This is a test car."},
    {"id": 230, "model": "INFINITI", "bland": "Q60 Convertible", "year": "2015", "description": "This is a test car."},
    {"id": 231, "model": "Buick", "bland": "Regal", "year": "2014", "description": "This is a test car."},
    {"id": 232, "model": "Chevrolet", "bland": "Camaro", "year": "2016", "description": "This is a test car."},
    {"id": 233, "model": "BMW", "bland": "1 Series", "year": "2013", "description": "This is a test car."},
    {"id": 234, "model": "MINI", "bland": "Clubman", "year": "2014", "description": "This is a test car."},
    {"id": 235, "model": "Hyundai", "bland": "Elantra Touring", "year": "2011", "description": "This is a test car."},
    {"id": 236, "model": "Chevrolet", "bland": "Cruze Limited", "year": "2016", "description": "This is a test car."},
    {"id": 237, "model": "Chevrolet", "bland": "SS", "year": "2016", "description": "This is a test car."},
    {"id": 238, "model": "Lexus", "bland": "RX 450h", "year": "2014", "description": "This is a test car."},
    {"id": 239, "model": "Dodge", "bland": "Challenger", "year": "2016", "description": "This is a test car."},
    {"id": 240, "model": "Dodge", "bland": "Dart", "year": "2015", "description": "This is a test car."},
    {"id": 241, "model": "Acura", "bland": "RLX", "year": "2015", "description": "This is a test car."},
    {"id": 242, "model": "Ford", "bland": "F-150", "year": "2014", "description": "This is a test car."},
    {"id": 243, "model": "Ford", "bland": "Fiesta", "year": "2014", "description": "This is a test car."},
    {"id": 244, "model": "Audi", "bland": "A3", "year": "2015", "description": "This is a test car."},
    {"id": 245, "model": "Mazda", "bland": "Mazda5", "year": "2015", "description": "This is a test car."},
    {"id": 246, "model": "Kia", "bland": "Rondo", "year": "2009", "description": "This is a test car."},
    {"id": 247, "model": "Hyundai", "bland": "Tucson", "year": "2013", "description": "This is a test car."},
    {"id": 248, "model": "Kia", "bland": "Forte5", "year": "2016", "description": "This is a test car."},
    {"id": 249, "model": "INFINITI", "bland": "Q50 Hybrid", "year": "2014", "description": "This is a test car."},
    {"id": 250, "model": "Honda", "bland": "Odyssey", "year": "2015", "description": "This is a test car."},
    {"id": 251, "model": "MINI", "bland": "Cooper Convertible", "year": "2012", "description": "This is a test car."},
    {"id": 252, "model": "Ford", "bland": "Escape", "year": "2016", "description": "This is a test car."},
    {"id": 253, "model": "Jaguar", "bland": "XJL", "year": "2013", "description": "This is a test car."},
    {"id": 254, "model": "Chevrolet", "bland": "Captiva Sport Fleet", "year": "2015",
     "description": "This is a test car."},
    {"id": 255, "model": "Audi", "bland": "A8 L", "year": "2011", "description": "This is a test car."},
    {"id": 256, "model": "Acura", "bland": "ILX", "year": "2016", "description": "This is a test car."},
    {"id": 257, "model": "Mercedes-Benz", "bland": "B-Class", "year": "2014", "description": "This is a test car."},
    {"id": 258, "model": "Land Rover", "bland": "Range Rover Sport", "year": "2013",
     "description": "This is a test car."},
    {"id": 259, "model": "Hyundai", "bland": "Genesis Coupe", "year": "2015", "description": "This is a test car."},
    {"id": 260, "model": "Buick", "bland": "LaCrosse", "year": "2013", "description": "This is a test car."},
    {"id": 261, "model": "INFINITI", "bland": "QX56", "year": "2011", "description": "This is a test car."},
    {"id": 262, "model": "Acura", "bland": "TL", "year": "2014", "description": "This is a test car."},
    {"id": 263, "model": "Hyundai", "bland": "Veloster", "year": "2016", "description": "This is a test car."},
    {"id": 264, "model": "Buick", "bland": "Lucerne", "year": "2011", "description": "This is a test car."},
    {"id": 265, "model": "Kia", "bland": "Sedona", "year": "2015", "description": "This is a test car."},
    {"id": 266, "model": "Lincoln", "bland": "MKZ Hybrid", "year": "2015", "description": "This is a test car."},
    {"id": 267, "model": "Ford", "bland": "Fusion Hybrid", "year": "2016", "description": "This is a test car."},
    {"id": 268, "model": "Hyundai", "bland": "Sonata", "year": "2016", "description": "This is a test car."},
    {"id": 269, "model": "Cadillac", "bland": "XTS", "year": "2013", "description": "This is a test car."},
    {"id": 270, "model": "Cadillac", "bland": "Escalade", "year": "2012", "description": "This is a test car."},
    {"id": 271, "model": "Ford", "bland": "Flex", "year": "2016", "description": "This is a test car."},
    {"id": 272, "model": "Dodge", "bland": "Journey", "year": "2015", "description": "This is a test car."},
    {"id": 273, "model": "Mercedes-Benz", "bland": "GLA", "year": "2016", "description": "This is a test car."},
    {"id": 274, "model": "Land Rover", "bland": "Range Rover Evoque", "year": "2015",
     "description": "This is a test car."},
    {"id": 275, "model": "INFINITI", "bland": "G37 Sedan", "year": "2011", "description": "This is a test car."},
    {"id": 276, "model": "Audi", "bland": "Q3", "year": "2016", "description": "This is a test car."},
    {"id": 277, "model": "Mitsubishi", "bland": "Outlander Sport", "year": "2016",
     "description": "This is a test car."},
    {"id": 278, "model": "Lexus", "bland": "IS 250C", "year": "2014", "description": "This is a test car."},
    {"id": 279, "model": "Audi", "bland": "S5", "year": "2014", "description": "This is a test car."},
    {"id": 280, "model": "Cadillac", "bland": "CTS-V", "year": "2012", "description": "This is a test car."},
    {"id": 281, "model": "Ford", "bland": "Fusion Energi", "year": "2016", "description": "This is a test car."},
    {"id": 282, "model": "BMW", "bland": "6 Series", "year": "2013", "description": "This is a test car."},
    {"id": 283, "model": "Lincoln", "bland": "MKZ Hybrid", "year": "2016", "description": "This is a test car."},
    {"id": 284, "model": "Audi", "bland": "A7", "year": "2013", "description": "This is a test car."},
    {"id": 285, "model": "Mitsubishi", "bland": "Outlander", "year": "2016", "description": "This is a test car."},
    {"id": 286, "model": "Hyundai", "bland": "Veloster Turbo", "year": "2016", "description": "This is a test car."},
    {"id": 287, "model": "GMC", "bland": "Terrain", "year": "2014", "description": "This is a test car."},
    {"id": 288, "model": "Mercedes-Benz", "bland": "SLK-Class", "year": "2012", "description": "This is a test car."},
    {"id": 289, "model": "INFINITI", "bland": "QX80", "year": "2014", "description": "This is a test car."},
    {"id": 290, "model": "Honda", "bland": "Element", "year": "2010", "description": "This is a test car."},
    {"id": 291, "model": "Chevrolet", "bland": "Colorado", "year": "2012", "description": "This is a test car."},
    {"id": 292, "model": "Buick", "bland": "Encore", "year": "2016", "description": "This is a test car."},
    {"id": 293, "model": "MINI", "bland": "Coupe", "year": "2015", "description": "This is a test car."},
    {"id": 294, "model": "INFINITI", "bland": "JX35", "year": "2013", "description": "This is a test car."},
    {"id": 295, "model": "Lexus", "bland": "IS 350", "year": "2016", "description": "This is a test car."},
    {"id": 296, "model": "Chevrolet", "bland": "Cruze Limited", "year": "2016", "description": "This is a test car."},
    {"id": 297, "model": "Chevrolet", "bland": "Trax", "year": "2016", "description": "This is a test car."},
    {"id": 298, "model": "Dodge", "bland": "Ram Pickup 1500", "year": "2010", "description": "This is a test car."},
    {"id": 299, "model": "Jeep", "bland": "Cherokee", "year": "2016", "description": "This is a test car."},
    {"id": 300, "model": "Jeep", "bland": "Wrangler Unlimited", "year": "2015", "description": "This is a test car."},
    {"id": 301, "model": "Acura", "bland": "MDX", "year": "2016", "description": "This is a test car."},
    {"id": 302, "model": "Audi", "bland": "A8", "year": "2013", "description": "This is a test car."},
    {"id": 303, "model": "Lexus", "bland": "GS 300", "year": "2006", "description": "This is a test car."},
    {"id": 304, "model": "Land Rover", "bland": "LR2", "year": "2014", "description": "This is a test car."},
    {"id": 305, "model": "Lexus", "bland": "ES 300h", "year": "2013", "description": "This is a test car."},
    {"id": 306, "model": "MINI", "bland": "Roadster", "year": "2014", "description": "This is a test car."},
    {"id": 307, "model": "Chevrolet", "bland": "Impala Limited", "year": "2014", "description": "This is a test car."},
    {"id": 308, "model": "Honda", "bland": "CR-Z", "year": "2016", "description": "This is a test car."},
    {"id": 309, "model": "Chevrolet", "bland": "Cruze", "year": "2014", "description": "This is a test car."},
    {"id": 310, "model": "Mercedes-Benz", "bland": "GLK", "year": "2015", "description": "This is a test car."},
    {"id": 311, "model": "INFINITI", "bland": "Q40", "year": "2015", "description": "This is a test car."},
    {"id": 312, "model": "Mazda", "bland": "CX-3", "year": "2016", "description": "This is a test car."},
    {"id": 313, "model": "BMW", "bland": "Z4", "year": "2013", "description": "This is a test car."},
    {"id": 314, "model": "Mercury", "bland": "Mountaineer", "year": "2010", "description": "This is a test car."},
    {"id": 315, "model": "Cadillac", "bland": "XT5", "year": "2017", "description": "This is a test car."},
    {"id": 316, "model": "Audi", "bland": "Q3", "year": "2016", "description": "This is a test car."},
    {"id": 317, "model": "Chrysler", "bland": "Town and Country", "year": "2015", "description": "This is a test car."},
    {"id": 318, "model": "Land Rover", "bland": "Range Rover", "year": "2011", "description": "This is a test car."},
]

PRODUCTS2CATEGORIES = [
    {"product_id": 1, "category_ids": [6]},
    {"product_id": 2, "category_ids": [6]},
    {"product_id": 3, "category_ids": [6]},
    {"product_id": 4, "category_ids": [6]},
    {"product_id": 5, "category_ids": [6]},
    {"product_id": 6, "category_ids": [6]},
    {"product_id": 7, "category_ids": [6]},
    {"product_id": 8, "category_ids": [6]},
    {"product_id": 9, "category_ids": [6]},
    {"product_id": 10, "category_ids": [6]},
    {"product_id": 11, "category_ids": [6]},

    {"product_id": 12, "category_ids": [5]},
    {"product_id": 13, "category_ids": [5]},
    {"product_id": 14, "category_ids": [5]},
    {"product_id": 15, "category_ids": [5]},
    {"product_id": 16, "category_ids": [5]},
    {"product_id": 17, "category_ids": [5]},
    {"product_id": 18, "category_ids": [5]},
    {"product_id": 19, "category_ids": [5]},
    {"product_id": 20, "category_ids": [5]},

    {"product_id": 21, "category_ids": [3]},
    {"product_id": 22, "category_ids": [3]},
    {"product_id": 23, "category_ids": [3]},
    {"product_id": 24, "category_ids": [3]},
    {"product_id": 25, "category_ids": [3]},
    {"product_id": 26, "category_ids": [3]},
    {"product_id": 27, "category_ids": [3]},
    {"product_id": 28, "category_ids": [3]},
    {"product_id": 29, "category_ids": [3]},
    {"product_id": 30, "category_ids": [3]},
    {"product_id": 31, "category_ids": [7]},
    {"product_id": 32, "category_ids": [7]},
    {"product_id": 33, "category_ids": [7]},
    {"product_id": 34, "category_ids": [7]},
    {"product_id": 35, "category_ids": [8]},
    {"product_id": 36, "category_ids": [8]},
    {"product_id": 37, "category_ids": [8]},
    {"product_id": 38, "category_ids": [7]},
    {"product_id": 39, "category_ids": [7]},
    {"product_id": 40, "category_ids": [8]},
    {"product_id": 41, "category_ids": [5]},
    {"product_id": 41, "category_ids": [5]},
    {"product_id": 42, "category_ids": [5]},
    {"product_id": 43, "category_ids": [5]},
    {"product_id": 44, "category_ids": [5]},
    {"product_id": 45, "category_ids": [5]},
    {"product_id": 46, "category_ids": [5]},
    {"product_id": 47, "category_ids": [5]},
    {"product_id": 48, "category_ids": [5]},
    {"product_id": 49, "category_ids": [5]},
    {"product_id": 50, "category_ids": [5]},
    {"product_id": 51, "category_ids": [5]},
    {"product_id": 52, "category_ids": [5]},
    {"product_id": 53, "category_ids": [5]},
    {"product_id": 54, "category_ids": [5]},
    {"product_id": 55, "category_ids": [5]},
    {"product_id": 56, "category_ids": [5]},
    {"product_id": 57, "category_ids": [5]},
    {"product_id": 58, "category_ids": [5]},
    {"product_id": 59, "category_ids": [5]},
    {"product_id": 60, "category_ids": [5]},
    {"product_id": 61, "category_ids": [5]},
    {"product_id": 62, "category_ids": [5]},
    {"product_id": 63, "category_ids": [5]},
    {"product_id": 64, "category_ids": [5]},
    {"product_id": 65, "category_ids": [9]},
    {"product_id": 66, "category_ids": [9]},
    {"product_id": 67, "category_ids": [9]},
    {"product_id": 68, "category_ids": [9]},
    {"product_id": 69, "category_ids": [9]},
    {"product_id": 70, "category_ids": [9]},
    {"product_id": 71, "category_ids": [9]},
    {"product_id": 72, "category_ids": [9]},
    {"product_id": 73, "category_ids": [9]},
    {"product_id": 74, "category_ids": [9]},
    {"product_id": 75, "category_ids": [9]},
    {"product_id": 76, "category_ids": [9]},
    {"product_id": 77, "category_ids": [9]},
    {"product_id": 78, "category_ids": [9]},
    {"product_id": 79, "category_ids": [9]},
    {"product_id": 80, "category_ids": [9]},
]

CARTS = [
    {"id": 1, "count": 2, "owner_id": 2, "product_id": 1, "is_selected": True},
    {"id": 2, "count": 3, "owner_id": 2, "product_id": 3, "is_selected": False},
    {"id": 3, "count": 1, "owner_id": 2, "product_id": 4, "is_selected": True},
    {"id": 4, "count": 2, "owner_id": 2, "product_id": 7, "is_selected": True},
]

PRODUCTIMAGEPATHS = [
    {"id": 1, "image_path": "../../static/storage/products/1043492022041147gp_product_gb1_989f849fc2692767106a8e9604ef9377.jpg", "product_id": 1},
    {"id": 2, "image_path": "../../static/storage/products/1044242022041134gp_product_gb1_989f849fc2692767106a8e9604ef9377.jpg", "product_id": 2},
    {"id": 3, "image_path": "../../static/storage/products/1058172022041138gp_product_c5x_91c04cb3e0e2f29847331c203c986614.jpg", "product_id": 3},
    {"id": 4, "image_path": "../../static/storage/products/1058352022041136gp_product_CF6_c0895dd5de951ac136e6d5dc04862a56.jpg", "product_id": 4},
    {"id": 5, "image_path": "../../static/storage/products/1058522022041192gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 5},
    {"id": 6, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 6},
    {"id": 7, "image_path": "../../static/storage/products/1058522022041192gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 7},
    {"id": 8, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 8},
    {"id": 9, "image_path": "../../static/storage/products/1058522022041192gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 9},
    {"id": 10, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 10},
    {"id": 11, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "product_id": 11},

    {"id": 12, "image_path": "../../static/storage/products/64357834534654357___-1.jpg", "product_id": 12},
    {"id": 13, "image_path": "../../static/storage/products/4687326536537_thumb_011.jpg", "product_id": 13},
    {"id": 14, "image_path": "../../static/storage/products/64723463876536573_thumb_0021.png", "product_id": 14},
    {"id": 15, "image_path": "../../static/storage/products/743534867537_thumb_11.jpg", "product_id": 15},
    {"id": 16, "image_path": "../../static/storage/products/12790846347956_thumb_a2.jpg", "product_id": 16},
    {"id": 17, "image_path": "../../static/storage/products/35467324587_Hybrid_Maple_540x540_735x735_9a1491d206e417dabe25ffb9a7256e44.jpg", "product_id": 17},
    {"id": 18, "image_path": "../../static/storage/products/347638754576357_2.jpg", "product_id": 18},
    {"id": 19, "image_path": "../../static/storage/products/462374658237_thumb_EEC3B1474CC2FF84F87750513DCFE138.jpg", "product_id": 19},
    {"id": 20, "image_path": "../../static/storage/products/463287567354_540x540_396x396_88f34b4b488bd561277141e6457f8ce5.jpg", "product_id": 20},

    {"id": 21, "image_path": "../../static/storage/products/64357834534654357__.jpg", "product_id": 21},
    {"id": 22, "image_path": "../../static/storage/products/64357834534654357__(1).jpg", "product_id": 22},
    {"id": 23, "image_path": "../../static/storage/products/64357834534654357____(1).jpg", "product_id": 23},
    {"id": 24, "image_path": "../../static/storage/products/64357834534654357____(2).jpg", "product_id": 24},
    {"id": 25, "image_path": "../../static/storage/products/64357834534654357______(1).jpg", "product_id": 25},
    {"id": 26, "image_path": "../../static/storage/products/64357834534654357cus.jpg", "product_id": 26},
    {"id": 27, "image_path": "../../static/storage/products/64357834534654357cus(1).jpg", "product_id": 27},
    {"id": 28, "image_path": "../../static/storage/products/a3f7b6565ee7.jpg", "product_id": 28},
    {"id": 29, "image_path": "../../static/storage/products/ee91d6d94ef9.jpg", "product_id": 29},
    {"id": 30, "image_path": "../../static/storage/products/fd1f5e44dcd5.jpg", "product_id": 30},
    {"id": 31, "image_path": "../../static/storage/products/violin_repair.jpg", "product_id": 31},
    {"id": 32, "image_path": "../../static/storage/products/Violin-Bridge-90-degree-angle.jpg", "product_id": 32},
    {"id": 33, "image_path": "../../static/storage/products/How-To-Replace-Your-Instruments-Bow-Hair-Index.jpg", "product_id": 33},
    {"id": 34, "image_path": "../../static/storage/products/85dcd0058981814a5f8e51052fce8f7f.jpg", "product_id": 34},
    {"id": 35, "image_path": "../../static/storage/products/Repair_03.jpg", "product_id": 35},
    {"id": 36, "image_path": "../../static/storage/products/repair-header.jpg", "product_id": 36},
    {"id": 37, "image_path": "../../static/storage/products/Drum-maintenance-hero-Copy.jpg", "product_id": 37},
    {"id": 38, "image_path": "../../static/storage/products/Cambridge_Woodwind_Makers_Flute_Repair_And_Care_course_with_Daniel_Bangham-e1559307146975-scaled-e1645459533582.jpg", "product_id": 38},
    {"id": 39, "image_path": "../../static/storage/products/How-to-Fix-Digital-Piano-Keys.jpg", "product_id": 39},
    {"id": 40, "image_path": "../../static/storage/products/How-to-Care-for-Your-Piano-5-1200x1800.jpg", "product_id": 40},
    {"id": 41, "image_path": "../../static/storage/products/YX-500R.jpg","product_id": 41},
    {"id": 42, "image_path": "../../static/storage/products/YX-500F.jpg", "product_id": 42},
    {"id": 43, "image_path": "../../static/storage/products/YX-135.jpg", "product_id": 43},
    {"id": 44, "image_path": "../../static/storage/products/YX-35G.jpg", "product_id": 44},
    {"id": 45, "image_path": "../../static/storage/products/YX-30G.jpg", "product_id": 45},
    {"id": 46, "image_path": "../../static/storage/products/YG-250D.jpg", "product_id": 46},
    {"id": 47, "image_path": "../../static/storage/products/YG-1210.jpg", "product_id": 47},
    {"id": 48, "image_path": "../../static/storage/products/YG-2500.jpg", "product_id": 48},
    {"id": 49, "image_path": "../../static/storage/products/YV-2030MS.jpg", "product_id": 49},
    {"id": 50, "image_path": "../../static/storage/products/YV-2700.jpg", "product_id": 50},
    {"id": 51, "image_path": "../../static/storage/products/YV-3710.jpg", "product_id": 51},
    {"id": 52, "image_path": "../../static/storage/products/YV-3910M.jpg", "product_id": 52},
    {"id": 53, "image_path": "../../static/storage/products/YV-4110M.jpg", "product_id": 53},
    {"id": 54, "image_path": "../../static/storage/products/YCH-6018.jpg", "product_id": 54},
    {"id": 55, "image_path": "../../static/storage/products/YCH-7018.jpg", "product_id": 55},
    {"id": 56, "image_path": "../../static/storage/products/CB-9000.jpg", "product_id": 56},
    {"id": 57, "image_path": "../../static/storage/products/CB-8000.jpg", "product_id": 57},
    {"id": 58, "image_path": "../../static/storage/products/CB-7000.jpg", "product_id": 58},
    {"id": 59, "image_path": "../../static/storage/products/CSM.jpg", "product_id": 59},
    {"id": 60, "image_path": "../../static/storage/products/OSM.jpg", "product_id": 60},
    {"id": 61, "image_path": "../../static/storage/products/OSM.jpg", "product_id": 61},
    {"id": 62, "image_path": "../../static/storage/products/TP-4300R.jpg", "product_id": 62},
    {"id": 63, "image_path": "../../static/storage/products/TP-6300R.jpg", "product_id": 63},
    {"id": 64, "image_path": "../../static/storage/products/TP-7300R.jpg", "product_id": 64},
    {"id": 65, "image_path": "../../static/storage/products/W-E3A-1.png", "product_id": 65},
    {"id": 66, "image_path": "../../static/storage/products/W-E3B-2.jpg", "product_id": 66},
    {"id": 67, "image_path": "../../static/storage/products/W-E5B-2.jpg", "product_id": 67},
    {"id": 68, "image_path": "../../static/storage/products/homeYH-L700A-2.jpg", "product_id": 68},
    {"id": 69, "image_path": "../../static/storage/products/homeYH-E500A-1.jpg", "product_id": 69},
    {"id": 70, "image_path": "../../static/storage/products/homeYH-E700A-1.jpg", "product_id": 70},
    {"id": 71, "image_path": "../../static/storage/products/proHPH-MT7.jpg", "product_id": 71},
    {"id": 72, "image_path": "../../static/storage/products/proHPH-MT7W.jpg", "product_id": 72},
    {"id": 73, "image_path": "../../static/storage/products/proHPH-MT8.jpg", "product_id": 73},
    {"id": 74, "image_path": "../../static/storage/products/proHPH-MT9.jpg", "product_id": 74},
    {"id": 75, "image_path": "../../static/storage/products/proHPH-MT9W.jpg", "product_id": 75},
    {"id": 76, "image_path": "../../static/storage/products/NS-AW350.jpg", "product_id": 76},
    {"id": 77, "image_path": "../../static/storage/products/NS-AW190.jpg", "product_id": 77},
    {"id": 78, "image_path": "../../static/storage/products/NS-AW570.jpg", "product_id": 78},
    {"id": 79, "image_path": "../../static/storage/products/NS-AW1941.jpg", "product_id": 79},
    {"id": 80, "image_path": "../../static/storage/products/NS-AW1942.jpg", "product_id": 80},
]

BLOGS = [
    {"id": 11, "title": "Guest Book", "content": "None", "author_id": 3},
    {"id": 1, "title": "Saxophone", "content": "This is a saxophone...", "author_id": 3},
    {"id": 2, "title": "I Hate Drums", "content": "I hate playing drums when I was...", "author_id": 3},
    {"id": 3, "title": "I Love Drums", "content": "I Love drums a lot. Back to...", "author_id": 3},
    {"id": 4, "title": "You can post blog WITHOUT IMAGE", "content": "I just found image is not necessary for a blog...", "author_id": 3},
    {"id": 5, "title": "Brass Is My Favorite", "content": "The sounds made by brasses are amazing...", "author_id": 3},
    {"id": 6, "title": "Brass Sounds Awful", "content": "I would rather use woods instead of brasses...", "author_id": 3},
    {"id": 7, "title": "I Love Piano", "content": "Piano probably is the best instrument...", "author_id": 3},
    {"id": 8, "title": "Piano is TOO DIFFICULT", "content": "Piano probably is the most difficult instrument...", "author_id": 3},
    {"id": 9, "title": "Cornet vs Trumpet | What's the difference?", "author_id": 3,
     "content": "Before we look at the difference, let’s first cover the basic elements of their design that are identical. Firstly, and most obviously, they are both made of the same material, Brass, have 3 valves and the sound is produced on both by ‘buzzing’ your lips. The tubing is also of an identical length (4 1/2 ft approx without valves depressed), although it is wound much tighter on a Cornet giving the initial appearance that it is shorter. As they are both the same length they therefore also play at the same pitch which is Bb on standard models."},
    {"id": 10, "title": "Briefly Noted: Alice Coote Schubertiade", "author_id": 3,
     "content": "At the end of March here in Washington, Alice Coote was the best part of the National Symphony Orchestra's performance of Mahler's Second Symphony, led by Michael Tilson Thomas. The British mezzo-soprano recorded this selection of twenty-one Schubert songs, back in December of 2017, in All Saints’ Church, East Finchley, in London. The program is a mixture of rather simple strophic songs and more complex pieces, some relative rarities alongside some of the most often heard songs in performances with new ideas to recommend them."}
]

BLOGIMAGEPATHS = [
    {"id": 1, "image_path": "../../static/img/blog/81v9wttUWbL._SX425_.jpg", "blog_id": 10},
    {"id": 2, "image_path": "../../static/img/blog/trumpet-facts_88be0d82-b6a7-4ffb-ace0-01c85aa3a7c7_600x.jpeg", "blog_id": 9},
    {"id": 3, "image_path": "../../static/img/blog/trumpet-bands.jpeg", "blog_id": 9},
    {"id": 4, "image_path": "../../static/img/blog/ptrumpet-learn.jpeg", "blog_id": 9},
    {"id": 5, "image_path": "../../static/img/blog/cornet-younger-people.jpeg", "blog_id": 9},
    {"id": 6, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "blog_id": 7},
    {"id": 11, "image_path": "../../static/storage/products/1059132022041196gp_product_s6x_2578a85a25d71f69c7dadf5cd592dd84.jpg", "blog_id": 8},
    {"id": 12, "image_path": "../../static/storage/products/64357834534654357___-1.jpg", "blog_id": 3},
    {"id": 13, "image_path": "../../static/storage/products/4687326536537_thumb_011.jpg", "blog_id": 3},
    {"id": 14, "image_path": "../../static/storage/products/64723463876536573_thumb_0021.png", "blog_id": 3},
    {"id": 15, "image_path": "../../static/storage/products/743534867537_thumb_11.jpg", "blog_id": 3},
    {"id": 16, "image_path": "../../static/storage/products/12790846347956_thumb_a2.jpg", "blog_id": 2},
    {"id": 17, "image_path": "../../static/storage/products/35467324587_Hybrid_Maple_540x540_735x735_9a1491d206e417dabe25ffb9a7256e44.jpg", "blog_id": 2},
    {"id": 18, "image_path": "../../static/storage/products/347638754576357_2.jpg", "blog_id": 2},
    {"id": 19, "image_path": "../../static/storage/products/462374658237_thumb_EEC3B1474CC2FF84F87750513DCFE138.jpg", "blog_id": 2},
    {"id": 20, "image_path": "../../static/storage/products/463287567354_540x540_396x396_88f34b4b488bd561277141e6457f8ce5.jpg", "blog_id": 2},
    {"id": 21, "image_path": "../../static/storage/products/64357834534654357__.jpg", "blog_id": 5},
    {"id": 22, "image_path": "../../static/storage/products/64357834534654357__(1).jpg", "blog_id": 5},
    {"id": 23, "image_path": "../../static/storage/products/64357834534654357____(1).jpg", "blog_id": 5},
    {"id": 24, "image_path": "../../static/storage/products/64357834534654357____(2).jpg", "blog_id": 5},
    {"id": 25, "image_path": "../../static/storage/products/64357834534654357______(1).jpg", "blog_id": 5},
    {"id": 26, "image_path": "../../static/storage/products/64357834534654357cus.jpg", "blog_id": 6},
    {"id": 27, "image_path": "../../static/storage/products/64357834534654357cus(1).jpg", "blog_id": 6},
    {"id": 28, "image_path": "../../static/storage/products/a3f7b6565ee7.jpg", "blog_id": 6},
    {"id": 29, "image_path": "../../static/storage/products/ee91d6d94ef9.jpg", "blog_id": 6},
    {"id": 30, "image_path": "../../static/storage/products/fd1f5e44dcd5.jpg", "blog_id": 1}
]

BLOGCOMMENTS = [
    {"id": 1, "body": "Hello", "blog_id": 1, "author_id": 3},
    {"id": 2, "body": "That's great", "blog_id": 2, "author_id": 3},
    {"id": 3, "body": "Awesome", "blog_id": 3, "author_id": 3},
    {"id": 4, "body": "Good", "blog_id": 4, "author_id": 3},
    {"id": 5, "body": "Ohhh, no", "blog_id": 5, "author_id": 3},
    {"id": 6, "body": "OK", "blog_id": 6, "author_id": 3},
    {"id": 7, "body": "Yeah", "blog_id": 7, "author_id": 3},
    {"id": 8, "body": "lol", "blog_id": 8, "author_id": 3}
]

ORDERS = [
    {"id": 1, "note": "Please be careful", "status": "Packing",
     "ship_way": "Delivery", "price": 3957, "name": "Ronnie", "gender": 1, "phone_number": 8848, "country": "China",
     "city": "Beijing", "street": "Youan", "detail": "building33", "priority": 1, "buyer_id": 2},
    {"id": 2, "note": "Please be vigilant", "status": "Created",
     "ship_way": "Delivery", "price": 2101, "name": "Er", "gender": 2, "phone_number": 88488, "country": "Spain",
     "city": "Madrid", "street": "Han", "detail": "1602", "priority": 0, "buyer_id": 2}
]

PRODUCTORDERS = [
    {"id": 1, "count": 1, "product_id": 4, "order_id": 1},
    {"id": 2, "count": 2, "product_id": 7, "order_id": 1},
    {"id": 3, "count": 2, "product_id": 66, "order_id": 2},
    {"id": 4, "count": 1, "product_id": 39, "order_id": 2},
    {"id": 5, "count": 1, "product_id": 13, "order_id": 2}
]
